spring.datasource.url=${DB_URL}
Spring.datasource.username=${DB_USERNAME}
Spring.datasource.password=${DB_PASSWORD}
Spring.datasource.driver-class-name=org.postgresql.Driver

Hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SHIPPING_EMAIL}
spring.mail.password=${PASSWORD_EMAIL}
dvwv tzsg apgq gxrn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true